import { ImageSourcePropType } from "react-native";

const icons = {
  google: require("@/assets/icons/google.png") as ImageSourcePropType,
  home: require("@/assets/icons/home.png") as ImageSourcePropType,
  search: require("@/assets/icons/search.png") as ImageSourcePropType,
  person: require("@/assets/icons/person.png") as ImageSourcePropType,
  bell: require("@/assets/icons/bell.png") as ImageSourcePropType,
  filter: require("@/assets/icons/filter.png") as ImageSourcePropType,
  star: require("@/assets/icons/star.png") as ImageSourcePropType,
  heart: require("@/assets/icons/heart.png") as ImageSourcePropType,
  backArrow: require("@/assets/icons/back-arrow.png") as ImageSourcePropType,
  calendar: require("@/assets/icons/calendar.png") as ImageSourcePropType,
  info: require("@/assets/icons/info.png") as ImageSourcePropType,
  language: require("@/assets/icons/language.png") as ImageSourcePropType,
  logout: require("@/assets/icons/logout.png") as ImageSourcePropType,
  people: require("@/assets/icons/people.png") as ImageSourcePropType,
  shield: require("@/assets/icons/shield.png") as ImageSourcePropType,
  wallet: require("@/assets/icons/wallet.png") as ImageSourcePropType,
  rightArrow: require("@/assets/icons/right-arrow.png") as ImageSourcePropType,
  send: require("@/assets/icons/send.png") as ImageSourcePropType,
  bed: require("@/assets/icons/bed.png") as ImageSourcePropType,
  bath: require("@/assets/icons/bath.png") as ImageSourcePropType,
  area: require("@/assets/icons/area.png") as ImageSourcePropType,
  chat: require("@/assets/icons/chat.png") as ImageSourcePropType,
  phone: require("@/assets/icons/phone.png") as ImageSourcePropType,
  carPark: require("@/assets/icons/car-park.png") as ImageSourcePropType,
  cutlery: require("@/assets/icons/cutlery.png") as ImageSourcePropType,
  dog: require("@/assets/icons/dog.png") as ImageSourcePropType,
  dumbell: require("@/assets/icons/dumbell.png") as ImageSourcePropType,
  laundry: require("@/assets/icons/laundry.png") as ImageSourcePropType,
  run: require("@/assets/icons/run.png") as ImageSourcePropType,
  swim: require("@/assets/icons/swim.png") as ImageSourcePropType,
  wifi: require("@/assets/icons/wifi.png") as ImageSourcePropType,
  location: require("@/assets/icons/location.png") as ImageSourcePropType,
  edit: require("@/assets/icons/edit.png") as ImageSourcePropType,
  close: require("@/assets/icons/close.png") as ImageSourcePropType,
} as const;

export default icons;